In [33]:
import pandas as pd
import requests
import json

pd.set_option("display.max_columns", None)

In [34]:
# url =  ("https://www.fema.gov/api/open/v2/PublicAssistanceFundedProjectsDetails")
url = ("https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries")
# url =  ("https://www.fema.gov/api/open/v1/FemaWebDisasterSummaries")
# url =  ("https://www.fema.gov/api/open/v1/FemaWebDisasterDeclarations")
response = requests.get(url)
response.status_code
data = response.json()
data
# public_assist = data['PublicAssistanceFundedProjectsDetails']
# disaster_summaries = data['FemaWebDisasterSummaries']
Declarations = data['DisasterDeclarationsSummaries']
# FW_DisasterDeclarations = data['FemaWebDisasterDeclarations']
# public_assist[0]
# disaster_summaries[0]
df = pd.DataFrame(Declarations)
# df = pd.DataFrame(public_assist)
# df = pd.DataFrame(disaster_summaries)
# df = pd.DataFrame(FW_DisasterDeclarations)
# print(df.shape)
print(df.columns)
df['disasterNumber'].nunique()
# df.head()
# print(df['totalNumberIaApproved'].isna().sum() * 100 / len(df))
# data.keys()
# data["metadata"]

Index(['femaDeclarationString', 'disasterNumber', 'state', 'declarationType',
       'declarationDate', 'fyDeclared', 'incidentType', 'declarationTitle',
       'ihProgramDeclared', 'iaProgramDeclared', 'paProgramDeclared',
       'hmProgramDeclared', 'incidentBeginDate', 'incidentEndDate',
       'disasterCloseoutDate', 'tribalRequest', 'fipsStateCode',
       'fipsCountyCode', 'placeCode', 'designatedArea',
       'declarationRequestNumber', 'lastIAFilingDate', 'incidentId', 'region',
       'designatedIncidentTypes', 'lastRefresh', 'hash', 'id'],
      dtype='str')

489

In [35]:
df['incidentType'].unique()

<StringArray>
[               'Fire',        'Severe Storm', 'Straight-Line Winds',
               'Flood',           'Hurricane',          'Biological',
        'Winter Storm',             'Tornado']
Length: 8, dtype: str

In [15]:
area_code = next((c for c in ['designatedArea'] if c in df.columns), None)
if area_code is not None:
    print('Column exists in the DataFrame:')
else:
    print('Column does not exist in the DataFrame.')

Column does not exist in the DataFrame.

In [27]:
# ds = pd.read_csv("../data/processed/final_selected_features.csv")
ds = pd.read_csv("../data/processed/fema_merged_dataset.csv")
print(ds.columns)
# print(ds.shape)
# ds.head()

Index(['disasterNumber', 'year', 'month', 'quarter', 'incident_duration_days',
       'incidentType', 'ihProgramDeclared', 'iaProgramDeclared',
       'paProgramDeclared', 'hmProgramDeclared', 'county_state', 'total_cost',
       'log_total_cost'],
      dtype='str')

In [31]:
ds.groupby("incidentType")["total_cost"].sum().sort_values(ascending=False).reset_index()

           incidentType    total_cost
0            Biological  9.018449e+12
1             Hurricane  8.663775e+12
2          Severe Storm  7.733644e+11
3                 Flood  4.284827e+11
4                  Fire  3.995231e+11
5      Severe Ice Storm  2.101114e+11
6        Tropical Storm  1.202225e+11
7            Earthquake  4.510215e+10
8             Snowstorm  3.735410e+10
9         Coastal Storm  2.174401e+10
10              Tornado  1.450101e+10
11         Winter Storm  3.870401e+09
12              Typhoon  2.168108e+09
13                Other  1.469172e+09
14        Mud/Landslide  1.123253e+09
15      Dam/Levee Break  3.817894e+08
16    Volcanic Eruption  1.707525e+08
17              Tsunami  1.700590e+08
18             Freezing  7.155992e+07
19  Tropical Depression  3.155671e+07
20            Terrorist  3.151149e+07
21             Chemical  1.475189e+07
22  Straight-Line Winds  4.694263e+06
23          Human Cause  4.293681e+06
24     Toxic Substances  4.073058e+06
25              Drought  7.925986e+04
26       Fishing Losses  0.000000e+00

In [29]:
ds.groupby("incidentType")["log_total_cost"].std().sort_values(ascending=False)

incidentType
Biological             9.440222
Volcanic Eruption      9.106232
Dam/Levee Break        9.043433
Earthquake             8.608359
Tropical Storm         8.588120
Hurricane              8.424816
Severe Ice Storm       7.875877
Typhoon                7.697653
Coastal Storm          7.679528
Human Cause            7.636328
Winter Storm           7.614691
Other                  7.596571
Straight-Line Winds    7.453778
Snowstorm              7.337341
Flood                  7.307873
Tornado                6.819979
Severe Storm           6.676780
Freezing               6.457412
Fire                   6.218276
Toxic Substances       6.125349
Mud/Landslide          5.931936
Drought                1.663219
Tsunami                1.008996
Terrorist              0.058618
Fishing Losses         0.000000
Chemical                    NaN
Tropical Depression         NaN
Name: log_total_cost, dtype: float64

In [28]:
# ds['incidentType']
ds.groupby("incidentType")["log_total_cost"].mean().sort_values(ascending=False).reset_index()

           incidentType  log_total_cost
0               Tsunami       16.390247
1             Terrorist       15.680736
2   Tropical Depression       15.321387
3              Chemical       14.309658
4         Mud/Landslide       12.799328
5          Severe Storm       12.676944
6      Severe Ice Storm       12.002973
7             Snowstorm       10.789677
8             Hurricane        9.983560
9                  Fire        9.543783
10                Other        9.070755
11        Coastal Storm        8.647065
12           Biological        8.500574
13         Winter Storm        8.420628
14       Tropical Storm        8.057204
15           Earthquake        7.484699
16    Volcanic Eruption        5.852947
17      Dam/Levee Break        5.832465
18              Typhoon        5.487516
19  Straight-Line Winds        5.415134
20                Flood        4.364582
21             Freezing        3.883903
22          Human Cause        3.818164
23              Tornado        3.761436
24     Toxic Substances        3.284877
25              Drought        0.245228
26       Fishing Losses        0.000000

In [9]:
data_df = pd.read_csv("../data/processed/fema_merged_dataset.csv")
# data_df.isna().sum()
print(data_df.columns)
data_df.shape

Index(['disasterNumber', 'year', 'month', 'quarter', 'incident_duration_days',
       'ihProgramDeclared', 'iaProgramDeclared', 'paProgramDeclared',
       'hmProgramDeclared', 'county_state', 'total_cost', 'log_total_cost'],
      dtype='str')

(5173, 12)

Linear Regression
Random Forest
XGBoost
Create models with list above.
Learn from the code below:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from category_encoders.target_encoder import TargetEncoder

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

target = 'Ticket_Price_GBP'

X = df.drop(columns=[target])
y = df[target]

nominal_column = ['Booking_Channel', 'Customer_Segment', 'Destination']

ordinal_column = ['Seat_Class', 'Route_Category', 'Loyalty_Status']

target_column = ['Origin']

num_features = [
    'Average_Spend_GBP',
    'Total_Seats',
    'Seats_Sold_Realized',
    'Remaining_Seats_Realized',
    'Demand_Index',
    'Days_Before_Travel',
    'Price_Premium',
    'Load_Factor'
]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('nominal', OneHotEncoder(drop='first'), nominal_column),
        ('ordinal', OrdinalEncoder(), ordinal_column),
        ('target_enc', TargetEncoder(), target_column),
        ('num', StandardScaler(), num_features)
    ],
    remainder='drop'
)

lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regression', LinearRegression())
])

lr_pipeline.fit(X_train, y_train)
lr_pred = lr_pipeline.predict(X_test)

print("MAE:", mean_absolute_error(y_test, lr_pred))
print("R2:", r2_score(y_test, lr_pred))
print("MSE:", mean_squared_error(y_test, lr_pred))

In [36]:
df.groupby("disasterNumber")["fipsCountyCode"].nunique().reset_index()

     disasterNumber  fipsCountyCode
0               388               3
1              3486               1
2              3500               1
3              3506               1
4              3519               1
..              ...             ...
489            5573               1
490            5574               1
491            5577               1
492            5578               1
493            5579               1

[494 rows x 2 columns]

In [10]:
# public_assist_df = pd.read_csv('/dataset/public_assistance.csv')
# public_assist_df.shape

In [ ]:

# def fetch_sample(url, record_key, limit=200):
#     r = requests.get(url, params={"$limit": limit})
#     r.raise_for_status()
#     data = r.json()
#     return pd.DataFrame(data[record_key])

# # Load samples
# decl_df = fetch_sample(
#     "https://www.fema.gov/api/open/v2/DisasterDeclarationsSummaries",
#     "DisasterDeclarationsSummaries"
# )

# pa_df = fetch_sample(
#     "https://www.fema.gov/api/open/v2/PublicAssistanceFundedProjectsDetails",
#     "PublicAssistanceFundedProjectsDetails"
# )

# web_df = fetch_sample(
#     "https://www.fema.gov/api/open/v1/FemaWebDisasterSummaries",
#     "FemaWebDisasterSummaries"
# )

In [ ]:
# decl_df["disasterNumber"].nunique()
# len(decl_df)

494

In [ ]:
# decl_df.head()
# pa_df.head()
# web_df.head()

(1000, 28)

In [ ]:
# def profile_df(df):
#     summary = pd.DataFrame({
#         "column": df.columns,
#         "dtype": df.dtypes.values,
#         "null_rate": df.isna().mean().values,
#         "n_unique": df.nunique().values,
#         "sample_values": [df[col].dropna().unique()[:3] for col in df.columns]
#     })
#     return summary

# decl_profile = profile_df(decl_df)
# pa_profile = profile_df(pa_df)
# web_profile = profile_df(web_df)

# decl_profile.head(20)

,column,dtype,null_rate,n_unique,sample_values
0,femaDeclarationString,str,0.000,494,"[FM-5529-OR, FM-5528-OR, FM-5527-OR]"
1,disasterNumber,int64,0.000,494,"[5529, 5528, 5527]"
2,state,str,0.000,36,"[OR, CA, AL]"
3,declarationType,str,0.000,3,"[FM, DR, EM]"
4,declarationDate,str,0.000,383,"[2024-08-09T00:00:00.000Z, 2024-08-06T00:00:00..."
5,fyDeclared,int64,0.000,15,"[2024, 2017, 2016]"
6,incidentType,str,0.000,8,"[Fire, Severe Storm, Straight-Line Winds]"
7,declarationTitle,str,0.000,473,"[LEE FALLS FIRE, ELK LANE FIRE, MILE MARKER 13..."
8,ihProgramDeclared,bool,0.000,2,"[False, True]"
9,iaProgramDeclared,bool,0.000,2,"[False, True]"
10,paProgramDeclared,bool,0.000,2,"[True, False]"
11,hmProgramDeclared,bool,0.000,2,"[True, False]"
12,incidentBeginDate,str,0.000,378,"[2024-08-08T00:00:00.000Z, 2024-08-04T00:00:00..."
13,incidentEndDate,str,0.089,350,"[2017-02-11T00:00:00.000Z, 2015-12-31T00:00:00..."
14,disasterCloseoutDate,str,0.657,137,"[2025-03-25T00:00:00.000Z, 2025-03-27T00:00:00..."
15,tribalRequest,bool,0.000,2,"[False, True]"
16,fipsStateCode,str,0.000,36,"[41, 06, 01]"
17,fipsCountyCode,str,0.000,191,"[067, 031, 017]"
18,placeCode,str,0.000,216,"[99067, 99031, 99017]"
19,designatedArea,str,0.000,518,"[Washington (County), Jefferson (County), Desc..."

In [68]:
merged = decl_df.merge(web_df, on="disasterNumber", how="left") \
                .merge(pa_df, on="disasterNumber", how="left")

merged.head()

,femaDeclarationString,disasterNumber,state,declarationType,declarationDate_x,fyDeclared,incidentType_x,declarationTitle,ihProgramDeclared,iaProgramDeclared,paProgramDeclared,hmProgramDeclared,incidentBeginDate,incidentEndDate,disasterCloseoutDate,tribalRequest,fipsStateCode,fipsCountyCode,placeCode,designatedArea,declarationRequestNumber,lastIAFilingDate,incidentId,region,designatedIncidentTypes,lastRefresh_x,hash_x,id_x,totalNumberIaApproved,totalAmountIhpApproved,totalAmountHaApproved,totalAmountOnaApproved,totalObligatedAmountPa,totalObligatedAmountCatAb,totalObligatedAmountCatC2g,paLoadDate,iaLoadDate,totalObligatedAmountHmgp,hash_y,lastRefresh_y,id_y,declarationDate_y,incidentType_y,pwNumber,applicationTitle,applicantId,damageCategoryCode,damageCategoryDescrip,projectStatus,projectProcessStep,projectSize,county,countyCode,stateAbbreviation,stateNumberCode,projectAmount,federalShareObligated,totalObligated,lastObligationDate,firstObligationDate,mitigationAmount,gmProjectId,gmApplicantId,lastRefresh,hash
0,FM-5529-OR,5529,OR,FM,2024-08-09T00:00:00.000Z,2024,Fire,LEE FALLS FIRE,False,False,True,True,2024-08-08T00:00:00.000Z,NaN,NaN,False,41,067,99067,Washington (County),24122,NaN,2024081001,10,R,2024-08-27T18:22:14.800Z,ae87cf3c6ed795015b714af7166c7c295b2b67c7,09e3f81a-5e16-4b72-b317-1c64e0cfa59c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FM-5528-OR,5528,OR,FM,2024-08-06T00:00:00.000Z,2024,Fire,ELK LANE FIRE,False,False,True,True,2024-08-04T00:00:00.000Z,NaN,NaN,False,41,031,99031,Jefferson (County),24116,NaN,2024080701,10,R,2024-08-27T18:22:14.800Z,432cf0995c47e3895cea696ede5621b810460501,59983f89-30bf-4888-b21b-62e8d57d9aac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FM-5527-OR,5527,OR,FM,2024-08-02T00:00:00.000Z,2024,Fire,MILE MARKER 132 FIRE,False,False,True,True,2024-08-02T00:00:00.000Z,NaN,NaN,False,41,017,99017,Deschutes (County),24111,NaN,2024080301,10,R,2024-08-27T18:22:14.800Z,2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa,8d13ecf0-bc2f-496b-8c9f-b2e73da832a0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DR-4312-CA,4312,CA,DR,2017-05-02T00:00:00.000Z,2017,Severe Storm,FLOODING,False,False,True,True,2017-02-08T00:00:00.000Z,2017-02-11T00:00:00.000Z,2025-03-25T00:00:00.000Z,True,06,000,60347,Resighini Rancheria (Indian Reservation),17035,NaN,2017041001,9,NaN,2025-03-26T20:21:32.579Z,432a3a64bdbb291ae26cf5a27a33deeabb380481,98a7c5bb-2346-45aa-a1ca-0399440d4f0b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DR-4251-AL,4251,AL,DR,2016-01-21T00:00:00.000Z,2016,Severe Storm,"SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS,...",False,False,True,True,2015-12-23T00:00:00.000Z,2015-12-31T00:00:00.000Z,2025-03-27T00:00:00.000Z,False,01,001,99001,Autauga (County),16003,NaN,2015122301,4,NaN,2025-03-27T12:21:46.559Z,dcd4ce6b37ee49875b3f1e32e9a8a16cd6a803d3,5229bbae-eee6-42b8-b277-edbafa8d6cb2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# merged['totalAmountIhpApproved'].isna().mean() * 100
# merged['incidentEndDate'].isna().value_counts(dropna=False)
# merged['iaLoadDate'].value_counts(dropna=False)
# merged["totalObligated"].isna().mean() * 100

nan

In [70]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   femaDeclarationString       1000 non-null   str
 1   disasterNumber              1000 non-null   int64
 2   state                       1000 non-null   str
 3   declarationType             1000 non-null   str
 4   declarationDate_x           1000 non-null   str
 5   fyDeclared                  1000 non-null   int64
 6   incidentType_x              1000 non-null   str
 7   declarationTitle            1000 non-null   str
 8   ihProgramDeclared           1000 non-null   bool
 9   iaProgramDeclared           1000 non-null   bool
 10  paProgramDeclared           1000 non-null   bool
 11  hmProgramDeclared           1000 non-null   bool
 12  incidentBeginDate           1000 non-null   str
 13  incidentEndDate             911 non-null    str
 14  disasterCloseoutDate        343 non-null    str
 15  tribalRequest               1000 non-null   bool
 16  fipsStateCode               1000 non-null   str
 17  fipsCountyCode              1000 non-null   str
 18  placeCode                   1000 non-null   str
 19  designatedArea              1000 non-null   str
 20  declarationRequestNumber    1000 non-null   str
 21  lastIAFilingDate            217 non-null    str
 22  incidentId                  1000 non-null   str
 23  region                      1000 non-null   int64
 24  designatedIncidentTypes     425 non-null    str
 25  lastRefresh_x               1000 non-null   str
 26  hash_x                      1000 non-null   str
 27  id_x                        1000 non-null   str
 28  totalNumberIaApproved       0 non-null      object
 29  totalAmountIhpApproved      0 non-null      object
 30  totalAmountHaApproved       0 non-null      object
 31  totalAmountOnaApproved      0 non-null      object
 32  totalObligatedAmountPa      127 non-null    float64
 33  totalObligatedAmountCatAb   112 non-null    float64
 34  totalObligatedAmountCatC2g  26 non-null     float64
 35  paLoadDate                  127 non-null    str
 36  iaLoadDate                  0 non-null      object
 37  totalObligatedAmountHmgp    165 non-null    float64
 38  hash_y                      165 non-null    str
 39  lastRefresh_y               165 non-null    str
 40  id_y                        165 non-null    str
 41  declarationDate_y           0 non-null      str
 42  incidentType_y              0 non-null      str
 43  pwNumber                    0 non-null      float64
 44  applicationTitle            0 non-null      str
 45  applicantId                 0 non-null      str
 46  damageCategoryCode          0 non-null      str
 47  damageCategoryDescrip       0 non-null      str
 48  projectStatus               0 non-null      str
 49  projectProcessStep          0 non-null      str
 50  projectSize                 0 non-null      str
 51  county                      0 non-null      str
 52  countyCode                  0 non-null      str
 53  stateAbbreviation           0 non-null      str
 54  stateNumberCode             0 non-null      str
 55  projectAmount               0 non-null      float64
 56  federalShareObligated       0 non-null      float64
 57  totalObligated              0 non-null      float64
 58  lastObligationDate          0 non-null      str
 59  firstObligationDate         0 non-null      str
 60  mitigationAmount            0 non-null      float64
 61  gmProjectId                 0 non-null      float64
 62  gmApplicantId               0 non-null      float64
 63  lastRefresh                 0 non-null      str
 64  hash                        0 non-null      str
dtypes: bool(5), float64(11), int64(3), object(5), str(41)
memory usage: 473.8+ KB

In [ ]:
# features = [
#     "incidentType_x",
#     "state",
#     "declarationType",
#     "fyDeclared",
#     "incidentBeginDate",
#     "incidentEndDate",
#     "declarationDate_x",
#     "ihProgramDeclared",
#     "iaProgramDeclared",
#     "paProgramDeclared",
#     "hmProgramDeclared",
#     "fipsStateCode"
# ]

# target_df = df.groupby("disasterNumber")["totalObligated"].sum().reset_index()
# target_df.rename(columns={"totalObligated": "total_cost"}, inplace=True)

In [ ]:
# BASE_URL = "https://www.fema.gov"


# ENDPOINTS = {
#     "DisasterDeclarationsSummaries": f"{BASE_URL}/api/open/v2/DisasterDeclarationsSummaries"
# }

# url = ENDPOINTS["DisasterDeclarationsSummaries"]

# r = requests.get(url, params={"$limit": 10})

# if r.status_code != 200:
#     raise Exception(f"Request failed: {r.status_code}")

# data = r.json()

# records = data["DisasterDeclarationsSummaries"]  # key exists in v2

# df = pd.DataFrame(records)

# df.to_csv("DisasterDeclarationsSummaries.csv", index=False)

# print("DisasterDeclarationsSummaries saved")

DisasterDeclarationsSummaries saved

In [90]:
# df = pd.read_csv("DisasterDeclarationsSummaries.csv")
# df.columns

In [54]:
# df.head()

In [ ]:
# # import requests
# # import pandas as pd

# BASE_URL = "https://www.fema.gov"

# ENDPOINTS = {
#     "PublicAssistanceFundedProjectsDetails": f"{BASE_URL}/api/open/v2/PublicAssistanceFundedProjectsDetails"
# }

# url = ENDPOINTS["PublicAssistanceFundedProjectsDetails"]

# r = requests.get(url, params={"$limit": 10})

# if r.status_code != 200:
#     raise Exception(f"Request failed: {r.status_code}")

# data = r.json()

# records = data["PublicAssistanceFundedProjectsDetails"]  # key exists in v2

# df = pd.DataFrame(records)

# df.to_csv("public_assistance.csv", index=False)

# print("public_assistance saved")

public_assistance saved

In [89]:
# data = pd.read_csv("public_assistance.csv")
# data.columns

In [34]:
# df.head()

In [ ]:
# BASE_URL = "https://www.fema.gov"

# ENDPOINTS = {
#     "disaster_summaries": f"{BASE_URL}/api/open/v1/FemaWebDisasterSummaries",
# }

# url = ENDPOINTS["disaster_summaries"]

# r = requests.get(url, params={"$limit": 10})

# if r.status_code != 200:
#     raise Exception(f"Request failed: {r.status_code}")

# data = r.json()

# records = data["FemaWebDisasterSummaries"]  # key exists in v1

# df = pd.DataFrame(records)

# df.to_csv("disaster_summaries.csv", index=False)

# print("disaster_summaries saved")

disaster_summaries saved

In [ ]:
# data_df = pd.read_csv("disaster_summaries.csv")
# data_df.shape

(1000, 14)

In [ ]:
# BASE_URL = "https://www.fema.gov"

# ENDPOINTS = {
#     "HazardMitigationAssistanceProjects": f"{BASE_URL}/api/open/v4/HazardMitigationAssistanceProjects"
# }

# url = ENDPOINTS["HazardMitigationAssistanceProjects"]

# r = requests.get(url, params={"$limit": 10})

# if r.status_code != 200:
#     raise Exception(f"Request failed: {r.status_code}")

# data = r.json()

# records = data["HazardMitigationAssistanceProjects"]  # key exists in v1

# df = pd.DataFrame(records)

# df.to_csv("HazardMitigationAssistance.csv", index=False)

# print("HazardMitigationAssistance saved")

HazardMitigationAssistance saved

In [88]:
# df_hazard = pd.read_csv("HazardMitigationAssistance.csv")
# df_hazard.columns

In [ ]:
# BASE_URL = "https://www.fema.gov"

# endpoint = url["links"][3]["href"]

# api_url = BASE_URL + endpoint

# response = requests.get(api_url).json()

# print(response)

{'links': [{'href': '/api/open/v4/HazardMitigationAssistanceMitigatedProperties', 'rel': 'HazardMitigationAssistanceMitigatedProperties', 'title': "This dataset contains the properties identified in the Hazard Mitigation Assistance (HMA) subapplications/subgrants from the NEMIS Mitigation and eGrants grants management systems. For details on the properties identified in the Hazard Mitigation Assistance (HMA) subapplications/subgrants not captured in these systems, visit https://www.fema.gov/openfema-data-page/hma-subapplications-project-site-inventories-v1. \n\nThis dataset contains information on the properties identified in the HMA subapplications/subgrants that have been submitted to or awarded in source systems mentioned above, as well as amendments made to the awarded subgrants. Sensitive information, such as Personally Identifiable Information (PII), has been removed to protect privacy. The information in this dataset has been deemed appropriate for publication to empower public knowledge of mitigation activities and the nature of HMA grant programs. For more information on the HMA grant programs, visit: https://www.fema.gov/grants/mitigation. \n\nThis dataset comes from the source systems mentioned above and is subject to a small percentage of human error. In some cases, data was not provided by the subapplicant, applicant, and/or entered into the grant management system. Due to the voluntary nature of the Hazard Mitigation Assistance Programs, not all properties in this dataset will be mitigated. This dataset is not intended to be used for any official federal financial reporting. \n\nIf you have media inquiries about this dataset, please email the FEMA Press Office at FEMA-Press-Office@fema.dhs.gov. For inquiries about FEMA's data and Open Government program, please email the OpenFEMA team at OpenFEMA@fema.dhs.gov.", 'type': 'application/json'}, {'href': '/api/open/v4/HazardMitigationAssistanceProjects', 'rel': 'HazardMitigationAssistanceProjects', 'title': "This dataset contains Hazard Mitigation Assistance (HMA) subapplications/subgrants from the NEMIS Mitigation and eGrants grants management systems. For details on HMA subapplications/subgrants not captured in these systems, visit https://www.fema.gov/openfema-data-page/hma-subapplications-v2. \n\nThis dataset contains information on the HMA subapplications/subgrants that have been submitted to or awarded in source systems mentioned above, as well as amendments made to the awarded subgrants. Sensitive information, such as Personally Identifiable Information (PII), has been removed to protect privacy. The information in this dataset has been deemed appropriate for publication to empower public knowledge of mitigation activities and the nature of HMA grant programs. For more information on the HMA grant programs, visit: https://www.fema.gov/grants/mitigation. \n\nThis dataset comes from the source systems mentioned above and is subject to a small percentage of human error. In some cases, data was not provided by the subapplicant, applicant, and/or entered into the grant management system. The financial information in this dataset is not derived from FEMA's official financial systems. Due to differences in reporting periods, status of obligations, and how business rules are applied, this financial information may differ slightly from official publication on public websites such as https://www.usaspending.gov. This dataset is not intended to be used for any official federal financial reporting. \n\nIf you have media inquiries about this dataset, please email the FEMA Press Office at FEMA-Press-Office@fema.dhs.gov. For inquiries about FEMA's data and Open Government program, please email the OpenFEMA team at OpenFEMA@fema.dhs.gov .", 'type': 'application/json'}, {'href': '/api/open/v4', 'rel': 'self', 'title': 'API Version 4 datasets', 'type': 'application/json'}, {'href': '/api/open', 'rel': 'parent', 'title': 'API version discovery', 'type': 'application/json'}], 'meta': {'version': 4, 'datasetCount': 2, 'lifeCycleStage': 'PUBLISHED'}}

In [ ]:
# BASE_URL = "https://www.fema.gov"

# for link in url["links"]:
#     if link["rel"] == "v4":
#         api_url = BASE_URL + link["href"]

# response = requests.get(api_url).json()

# print(response)

{'links': [{'href': '/api/open/v4/HazardMitigationAssistanceMitigatedProperties', 'rel': 'HazardMitigationAssistanceMitigatedProperties', 'title': "This dataset contains the properties identified in the Hazard Mitigation Assistance (HMA) subapplications/subgrants from the NEMIS Mitigation and eGrants grants management systems. For details on the properties identified in the Hazard Mitigation Assistance (HMA) subapplications/subgrants not captured in these systems, visit https://www.fema.gov/openfema-data-page/hma-subapplications-project-site-inventories-v1. \n\nThis dataset contains information on the properties identified in the HMA subapplications/subgrants that have been submitted to or awarded in source systems mentioned above, as well as amendments made to the awarded subgrants. Sensitive information, such as Personally Identifiable Information (PII), has been removed to protect privacy. The information in this dataset has been deemed appropriate for publication to empower public knowledge of mitigation activities and the nature of HMA grant programs. For more information on the HMA grant programs, visit: https://www.fema.gov/grants/mitigation. \n\nThis dataset comes from the source systems mentioned above and is subject to a small percentage of human error. In some cases, data was not provided by the subapplicant, applicant, and/or entered into the grant management system. Due to the voluntary nature of the Hazard Mitigation Assistance Programs, not all properties in this dataset will be mitigated. This dataset is not intended to be used for any official federal financial reporting. \n\nIf you have media inquiries about this dataset, please email the FEMA Press Office at FEMA-Press-Office@fema.dhs.gov. For inquiries about FEMA's data and Open Government program, please email the OpenFEMA team at OpenFEMA@fema.dhs.gov.", 'type': 'application/json'}, {'href': '/api/open/v4/HazardMitigationAssistanceProjects', 'rel': 'HazardMitigationAssistanceProjects', 'title': "This dataset contains Hazard Mitigation Assistance (HMA) subapplications/subgrants from the NEMIS Mitigation and eGrants grants management systems. For details on HMA subapplications/subgrants not captured in these systems, visit https://www.fema.gov/openfema-data-page/hma-subapplications-v2. \n\nThis dataset contains information on the HMA subapplications/subgrants that have been submitted to or awarded in source systems mentioned above, as well as amendments made to the awarded subgrants. Sensitive information, such as Personally Identifiable Information (PII), has been removed to protect privacy. The information in this dataset has been deemed appropriate for publication to empower public knowledge of mitigation activities and the nature of HMA grant programs. For more information on the HMA grant programs, visit: https://www.fema.gov/grants/mitigation. \n\nThis dataset comes from the source systems mentioned above and is subject to a small percentage of human error. In some cases, data was not provided by the subapplicant, applicant, and/or entered into the grant management system. The financial information in this dataset is not derived from FEMA's official financial systems. Due to differences in reporting periods, status of obligations, and how business rules are applied, this financial information may differ slightly from official publication on public websites such as https://www.usaspending.gov. This dataset is not intended to be used for any official federal financial reporting. \n\nIf you have media inquiries about this dataset, please email the FEMA Press Office at FEMA-Press-Office@fema.dhs.gov. For inquiries about FEMA's data and Open Government program, please email the OpenFEMA team at OpenFEMA@fema.dhs.gov .", 'type': 'application/json'}, {'href': '/api/open/v4', 'rel': 'self', 'title': 'API Version 4 datasets', 'type': 'application/json'}, {'href': '/api/open', 'rel': 'parent', 'title': 'API version discovery', 'type': 'application/json'}], 'meta': {'version': 4, 'datasetCount': 2, 'lifeCycleStage': 'PUBLISHED'}}

In [ ]:
# Extract the API URL from the links - using the v4 API endpoint as an example
# Replace 'your-api-domain' with your actual API domain
# BASE_URL = "https://www.fema.gov/api/open"
# api_endpoint = url["links"][3]["href"]  # v4 API
# api_url = BASE_URL + api_endpoint
# response = requests.get(api_url).json()

{'metadata': {'skip': 0, 'select': None, 'rundate': '2026-03-16T18:55:49.986Z', 'top': 1000, 'filter': '', 'format': 'json', 'metadata': True, 'orderby': '', 'entityname': 'DisasterDeclarationsSummaries', 'version': 'v2', 'url': '/api/open/v2/DisasterDeclarationsSummaries', 'count': 0}, 'DisasterDeclarationsSummaries': [{'femaDeclarationString': 'FM-5529-OR', 'disasterNumber': 5529, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-08-09T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'LEE FALLS FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-08-08T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '067', 'placeCode': '99067', 'designatedArea': 'Washington (County)', 'declarationRequestNumber': '24122', 'lastIAFilingDate': None, 'incidentId': '2024081001', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'ae87cf3c6ed795015b714af7166c7c295b2b67c7', 'id': '09e3f81a-5e16-4b72-b317-1c64e0cfa59c'}, {'femaDeclarationString': 'FM-5528-OR', 'disasterNumber': 5528, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-08-06T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'ELK LANE FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-08-04T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '031', 'placeCode': '99031', 'designatedArea': 'Jefferson (County)', 'declarationRequestNumber': '24116', 'lastIAFilingDate': None, 'incidentId': '2024080701', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '432cf0995c47e3895cea696ede5621b810460501', 'id': '59983f89-30bf-4888-b21b-62e8d57d9aac'}, {'femaDeclarationString': 'FM-5527-OR', 'disasterNumber': 5527, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-08-02T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'MILE MARKER 132 FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-08-02T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '017', 'placeCode': '99017', 'designatedArea': 'Deschutes (County)', 'declarationRequestNumber': '24111', 'lastIAFilingDate': None, 'incidentId': '2024080301', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '2f21d90cb6bc64b0d4121aa3f18d852bbb4b11fa', 'id': '8d13ecf0-bc2f-496b-8c9f-b2e73da832a0'}, {'femaDeclarationString': 'DR-4312-CA', 'disasterNumber': 4312, 'state': 'CA', 'declarationType': 'DR', 'declarationDate': '2017-05-02T00:00:00.000Z', 'fyDeclared': 2017, 'incidentType': 'Severe Storm', 'declarationTitle': 'FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2017-02-08T00:00:00.000Z', 'incidentEndDate': '2017-02-11T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-25T00:00:00.000Z', 'tribalRequest': True, 'fipsStateCode': '06', 'fipsCountyCode': '000', 'placeCode': '60347', 'designatedArea': 'Resighini Rancheria (Indian Reservation)', 'declarationRequestNumber': '17035', 'lastIAFilingDate': None, 'incidentId': '2017041001', 'region': 9, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-26T20:21:32.579Z', 'hash': '432a3a64bdbb291ae26cf5a27a33deeabb380481', 'id': '98a7c5bb-2346-45aa-a1ca-0399440d4f0b'}, {'femaDeclarationString': 'DR-4251-AL', 'disasterNumber': 4251, 'state': 'AL', 'declarationType': 'DR', 'declarationDate': '2016-01-21T00:00:00.000Z', 'fyDeclared': 2016, 'incidentType': 'Severe Storm', 'declarationTitle': 'SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS, AND FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2015-12-23T00:00:00.000Z', 'incidentEndDate': '2015-12-31T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-27T00:00:00.000Z', 'tribalRequest': False, 'fipsStateCode': '01', 'fipsCountyCode': '001', 'placeCode': '99001', 'designatedArea': 'Autauga (County)', 'declarationRequestNumber': '16003', 'lastIAFilingDate': None, 'incidentId': '2015122301', 'region': 4, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-27T12:21:46.559Z', 'hash': 'dcd4ce6b37ee49875b3f1e32e9a8a16cd6a803d3', 'id': '5229bbae-eee6-42b8-b277-edbafa8d6cb2'}, {'femaDeclarationString': 'DR-4251-AL', 'disasterNumber': 4251, 'state': 'AL', 'declarationType': 'DR', 'declarationDate': '2016-01-21T00:00:00.000Z', 'fyDeclared': 2016, 'incidentType': 'Severe Storm', 'declarationTitle': 'SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS, AND FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2015-12-23T00:00:00.000Z', 'incidentEndDate': '2015-12-31T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-27T00:00:00.000Z', 'tribalRequest': False, 'fipsStateCode': '01', 'fipsCountyCode': '005', 'placeCode': '99005', 'designatedArea': 'Barbour (County)', 'declarationRequestNumber': '16003', 'lastIAFilingDate': None, 'incidentId': '2015122301', 'region': 4, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-27T12:21:46.559Z', 'hash': '5b8478f80e09732d1f5195b604b0a3b8ca396a01', 'id': '2155164c-0c07-4da4-b5d1-d24a831d9bdc'}, {'femaDeclarationString': 'DR-4251-AL', 'disasterNumber': 4251, 'state': 'AL', 'declarationType': 'DR', 'declarationDate': '2016-01-21T00:00:00.000Z', 'fyDeclared': 2016, 'incidentType': 'Severe Storm', 'declarationTitle': 'SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS, AND FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2015-12-23T00:00:00.000Z', 'incidentEndDate': '2015-12-31T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-27T00:00:00.000Z', 'tribalRequest': False, 'fipsStateCode': '01', 'fipsCountyCode': '009', 'placeCode': '99009', 'designatedArea': 'Blount (County)', 'declarationRequestNumber': '16003', 'lastIAFilingDate': None, 'incidentId': '2015122301', 'region': 4, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-27T12:21:46.559Z', 'hash': '2aeb06b619f8ac8f58c936d883f04b6ba32539dd', 'id': '2e772244-38aa-4cce-8f9d-cb3cec41a7af'}, {'femaDeclarationString': 'DR-4251-AL', 'disasterNumber': 4251, 'state': 'AL', 'declarationType': 'DR', 'declarationDate': '2016-01-21T00:00:00.000Z', 'fyDeclared': 2016, 'incidentType': 'Severe Storm', 'declarationTitle': 'SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS, AND FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2015-12-23T00:00:00.000Z', 'incidentEndDate': '2015-12-31T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-27T00:00:00.000Z', 'tribalRequest': False, 'fipsStateCode': '01', 'fipsCountyCode': '011', 'placeCode': '99011', 'designatedArea': 'Bullock (County)', 'declarationRequestNumber': '16003', 'lastIAFilingDate': None, 'incidentId': '2015122301', 'region': 4, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-27T12:21:46.559Z', 'hash': '9e61dc26a6112528d4db9aeabb2aabc18b944590', 'id': '03312824-daf7-4b58-a88a-ae844d72e6d1'}, {'femaDeclarationString': 'DR-4251-AL', 'disasterNumber': 4251, 'state': 'AL', 'declarationType': 'DR', 'declarationDate': '2016-01-21T00:00:00.000Z', 'fyDeclared': 2016, 'incidentType': 'Severe Storm', 'declarationTitle': 'SEVERE STORMS, TORNADOES, STRAIGHT-LINE WINDS, AND FLOODING', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2015-12-23T00:00:00.000Z', 'incidentEndDate': '2015-12-31T00:00:00.000Z', 'disasterCloseoutDate': '2025-03-27T00:00:00.000Z', 'tribalRequest': False, 'fipsStateCode': '01', 'fipsCountyCode': '013', 'placeCode': '99013', 'designatedArea': 'Butler (County)', 'declarationRequestNumber': '16003', 'lastIAFilingDate': None, 'incidentId': '2015122301', 'region': 4, 'designatedIncidentTypes': None, 'lastRefresh': '2025-03-27T12:21:46.559Z', 'hash': '9a77fca608b697db636cda43ba5f47b785e7dff0', 'id': 'e3a71c7d-3351-4ee8-96a6-9f1498237a65'}, {'femaDeclarationString': 'FM-5516-OR', 'disasterNumber': 5516, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-22T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'DURKEE FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-21T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '001', 'placeCode': '99001', 'designatedArea': 'Baker (County)', 'declarationRequestNumber': '24093', 'lastIAFilingDate': None, 'incidentId': '2024072301', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '45ff69fccf92d0d834cbdfa43863f27a117e64a1', 'id': 'f04e205c-f078-44f3-a41c-e99832a27237'}, {'femaDeclarationString': 'FM-5516-OR', 'disasterNumber': 5516, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-22T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'DURKEE FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-21T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '045', 'placeCode': '99045', 'designatedArea': 'Malheur (County)', 'declarationRequestNumber': '24093', 'lastIAFilingDate': None, 'incidentId': '2024072301', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '3fb7fb2fd4a72c15f0e171ad2dc7493c1b794b2d', 'id': '60983d05-03a4-4b66-90e6-f7889e15fd7d'}, {'femaDeclarationString': 'FM-5514-OR', 'disasterNumber': 5514, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-21T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'BATTLE MOUNTAIN FIRE COMPLEX', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-21T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '023', 'placeCode': '99023', 'designatedArea': 'Grant (County)', 'declarationRequestNumber': '24092', 'lastIAFilingDate': None, 'incidentId': '2024072202', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'e7da1792be5f3f783ce34ff85a62c584327c4a0d', 'id': '45427119-abd1-4c6f-b876-d37d55cf97bf'}, {'femaDeclarationString': 'FM-5514-OR', 'disasterNumber': 5514, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-21T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'BATTLE MOUNTAIN FIRE COMPLEX', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-21T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '049', 'placeCode': '99049', 'designatedArea': 'Morrow (County)', 'declarationRequestNumber': '24092', 'lastIAFilingDate': None, 'incidentId': '2024072202', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '98ae6ac4936262d4e0be961104cb3361be870434', 'id': 'f3839077-b1f5-4eba-852e-d1db1da541ac'}, {'femaDeclarationString': 'FM-5514-OR', 'disasterNumber': 5514, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-21T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'BATTLE MOUNTAIN FIRE COMPLEX', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-21T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '059', 'placeCode': '99059', 'designatedArea': 'Umatilla (County)', 'declarationRequestNumber': '24092', 'lastIAFilingDate': None, 'incidentId': '2024072202', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'ecf955791b9c038ec43ffb8fbdcfbebbf98d6bdf', 'id': 'd0deaa82-4668-4346-9a9f-33db099c2fc5'}, {'femaDeclarationString': 'FM-5513-OR', 'disasterNumber': 5513, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-21T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'BONEYARD FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-20T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '023', 'placeCode': '99023', 'designatedArea': 'Grant (County)', 'declarationRequestNumber': '24091', 'lastIAFilingDate': None, 'incidentId': '2024072101', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'd6dc2b751eb9450eb1c42308047db100f19d9e1b', 'id': 'ee206396-9fe8-4f37-b973-b0514410fdee'}, {'femaDeclarationString': 'FM-5512-OR', 'disasterNumber': 5512, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-18T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'FALLS FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-18T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '023', 'placeCode': '99023', 'designatedArea': 'Grant (County)', 'declarationRequestNumber': '24090', 'lastIAFilingDate': None, 'incidentId': '2024071901', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '52f8fadf76e67cd79efd181e2acc778c42073d04', 'id': '1ae19176-efcc-4b70-a1f6-d7780e07d03b'}, {'femaDeclarationString': 'FM-5512-OR', 'disasterNumber': 5512, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-18T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'FALLS FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-18T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '025', 'placeCode': '99025', 'designatedArea': 'Harney (County)', 'declarationRequestNumber': '24090', 'lastIAFilingDate': None, 'incidentId': '2024071901', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'bba05ae451c567b32a7034ef1daa5aa8aef99a6e', 'id': 'e1ace295-e303-42e5-b918-d03810a466a3'}, {'femaDeclarationString': 'FM-5511-OR', 'disasterNumber': 5511, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-18T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'LONE ROCK FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-17T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '021', 'placeCode': '99021', 'designatedArea': 'Gilliam (County)', 'declarationRequestNumber': '24089', 'lastIAFilingDate': None, 'incidentId': '2024071801', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': 'bb62761b664195246787c7b0e871290944fc4f46', 'id': 'c80ffc22-fa37-4d9b-a2f7-7d04d4944eae'}, {'femaDeclarationString': 'FM-5511-OR', 'disasterNumber': 5511, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-18T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'LONE ROCK FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-17T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '049', 'placeCode': '99049', 'designatedArea': 'Morrow (County)', 'declarationRequestNumber': '24089', 'lastIAFilingDate': None, 'incidentId': '2024071801', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '1de76041457208b989b13e017b37cb756d395607', 'id': 'fffce5f4-378e-4aff-af18-55ab28c7323d'}, {'femaDeclarationString': 'FM-5511-OR', 'disasterNumber': 5511, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-18T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'LONE ROCK FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-17T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '41', 'fipsCountyCode': '069', 'placeCode': '99069', 'designatedArea': 'Wheeler (County)', 'declarationRequestNumber': '24089', 'lastIAFilingDate': None, 'incidentId': '2024071801', 'region': 10, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '89b318cc543591f6bfceace9211cf8c13a2a19c9', 'id': 'd4d538ce-7180-4c08-b283-58627bdbf97b'}, {'femaDeclarationString': 'FM-5507-MT', 'disasterNumber': 5507, 'state': 'MT', 'declarationType': 'FM', 'declarationDate': '2024-07-12T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'HORSE GULCH FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-09T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '30', 'fipsCountyCode': '007', 'placeCode': '99007', 'designatedArea': 'Broadwater (County)', 'declarationRequestNumber': '24085', 'lastIAFilingDate': None, 'incidentId': '2024071301', 'region': 8, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '2fd4f28f03860f50a4036d09dd01fe5114e60c0f', 'id': '64b35075-676d-4cda-909f-898535f8ca56'}, {'femaDeclarationString': 'FM-5507-MT', 'disasterNumber': 5507, 'state': 'MT', 'declarationType': 'FM', 'declarationDate': '2024-07-12T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationTitle': 'HORSE GULCH FIRE', 'ihProgramDeclared': False, 'iaProgramDeclared': False, 'paProgramDeclared': True, 'hmProgramDeclared': True, 'incidentBeginDate': '2024-07-09T00:00:00.000Z', 'incidentEndDate': None, 'disasterCloseoutDate': None, 'tribalRequest': False, 'fipsStateCode': '30', 'fipsCountyCode': '049', 'placeCode': '99049', 'designatedArea': 'Lewis and Clark (County)', 'declarationRequestNumber': '24085', 'lastIAFilingDate': None, 'incidentId': '2024071301', 'region': 8, 'designatedIncidentTypes': 'R', 'lastRefresh': '2024-08-27T18:22:14.800Z', 'hash': '2dae8cf46e42c196025651c916e6118eefbc693e', 'id': '19e28113-9160-46db-8414-bf44fd27de25'}, {'femaDeclarationString': 'FM-5506-OR', 'disasterNumber': 5506, 'state': 'OR', 'declarationType': 'FM', 'declarationDate': '2024-07-11T00:00:00.000Z', 'fyDeclared': 2024, 'incidentType': 'Fire', 'declarationT

In [ ]:
# BASE_URL = "https://www.fema.gov/api/open"

# ENDPOINTS = {
#     "declarations": f"{BASE_URL}/v2/DisasterDeclarationsSummaries",
#     "public_assistance": f"{BASE_URL}/v2/PublicAssistanceFundedProjectsDetails",
#     "disaster_summaries": f"{BASE_URL}/v1/FemaWebDisasterSummaries",
# }

# response = requests.get(ENDPOINTS["declarations"])
# data = response.json()

# print(data)